stages:
  - deploy

cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository

variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  IP_ADDRESS: "192.168.75.124"
  GIT_DEPTH: "0"


api:
  stage: deploy
  image: maven:3.8.8-eclipse-temurin-21-alpine # docker image with Maven
  only:
    - main
  before_script: 
    - ./ci/setup-mvn-proxy.sh
    # Useful only for debugging
    #- cat ~/.m2/settings.xml
    - chmod 400 "$CI_SSH_KEY"
   

  script:
    - apt update && apt install -y openssh-client
    - cd users
    - mvn clean package
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY target/users.war gitlabci@$IP_ADDRESS:/opt/tomcat/webapps/api.war
