stages:
  - deploy

cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository

variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  IP_ADDRESS: "192.168.75.124"
  GIT_DEPTH: "0"


api-USERS-deploy:
  stage: deploy
  image: maven:3.8.8-eclipse-temurin-21-alpine # docker image with Maven
  only:
    - main
  before_script: 
    - ./ci/setup-mvn-proxy.sh
    # Useful only for debugging
    #- cat ~/.m2/settings.xml
    - chmod 400 $CI_SSH_KEY

  script:
    - apk add --no-cache openssh-client
    - cd users
    - mvn clean package
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY target/users.war gitlabci@$IP_ADDRESS:/opt/tomcat/webapps/users.war

api-Game-deploy:
  stage: deploy
  image: node:20-alpine # docker image with Node.js
  only:
    - main
  before_script:
    - apk add --no-cache openssh-client
    - chmod 400 $CI_SSH_KEY

  script:
    - cd api
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY -r * gitlabci@$IP_ADDRESS:/opt/nodejs/api/
    - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY gitlabci@$IP_ADDRESS "cd /opt/nodejs/api/ && npm install && pm2 start index.js"

    
